import itertools
import time
char = []
print('PASSWORD LIST GENERATOR\nDEVELOPED BY M02K')
print('ENTER 20 WORDS FOR PASSWORD LIST')
print('USE * , @ , - FOR BETTER AND MODERN PASSWORD LIST ')
n1 = input('Enter word:1 ')
n2 = input('Enter word:2 ')
n3 = input('Enter word:3 ')
n4 = input('Enter word:4 ')
n5 = input('Enter word:5 ')
n6 = input('Enter word:6 ')
n7 = input('Enter word:7 ')
n8 = input('Enter word:8 ')
n9 = input('Enter word:9 ')
n10 = input('Enter word:10 ')
n11 = input('Enter word:11 ')
n12 = input('Enter word:12 ')
n13 = input('Enter word:13 ')
n14 = input('Enter word:14 ')
n15 = input('Enter word:15 ')
n16 = input('Enter word:16 ')
n17 = input('Enter word:17 ')
n18 = input('Enter word:18 ')
n19 = input('Enter word:19 ')
n20 = input('Enter word:20 ')

char.append(n1)
char.append(n2)
char.append(n3)
char.append(n4)
char.append(n5)
char.append(n6)
char.append(n7)
char.append(n8)
char.append(n9)
char.append(n10)
char.append(n11)
char.append(n12)
char.append(n13)
char.append(n14)
char.append(n15)
char.append(n16)
char.append(n17)
char.append(n18)
char.append(n19)
char.append(n20)

time.sleep(2.0)
n = 2
file = open('wordlist.txt' , 'a')
file.write('m02k')
for xs in itertools.product(char, repeat=n):
	plist = ''.join(xs)
	enter = file.write('\n'+plist)

print('file created wordlist.txt')
print(' regards M02k ')	